// <auto-generated />
using HastaneUygulamasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HastaneUygulamasi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240606163837_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HastaneUygulamasi.Models.Hastalar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DogumTarihi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HastaAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Katid")
                        .HasColumnType("int");

                    b.Property<int>("Odaid")
                        .HasColumnType("int");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("id");

                    b.HasIndex("Katid");

                    b.HasIndex("Odaid");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("HastaneUygulamasi.Models.Katlar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("KatNumarası")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Katlars");
                });

            modelBuilder.Entity("HastaneUygulamasi.Models.Odalar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("OdaNumarası")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Odalars");
                });

            modelBuilder.Entity("HastaneUygulamasi.Models.Hastalar", b =>
                {
                    b.HasOne("HastaneUygulamasi.Models.Katlar", "Katlar")
                        .WithMany("Hastalars")
                        .HasForeignKey("Katid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneUygulamasi.Models.Odalar", "Odalar")
                        .WithMany("Hastalars")
                        .HasForeignKey("Odaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katlar");

                    b.Navigation("Odalar");
                });

            modelBuilder.Entity("HastaneUygulamasi.Models.Katlar", b =>
                {
                    b.Navigation("Hastalars");
                });

            modelBuilder.Entity("HastaneUygulamasi.Models.Odalar", b =>
                {
                    b.Navigation("Hastalars");
                });
#pragma warning restore 612, 618
        }
    }
}
